#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-tyler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-tyler
  template:
    metadata:
      labels:
        app: prod-stedi-tyler
    spec:
      containers:
        - name: prod-stedi-tyler
          image: gcr.io/cubs-consulting/stedi # this image needs to refer to the new artifact repositiory
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-tyler
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-tyler"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tyler-twilio-dev
                  key: twilio_token
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-tyler-nodeport
spec:
  selector:
    app: prod-stedi-tyler
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-tyler-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-tyler-public # this IP has not been created yet - need to create this first
    networking.gke.io/managed-certificates: prod-stedi-tyler-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-tyler-nodeport # this needs to match line 53
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-tyler-certificate # needs to macth line 68
spec:
  domains:
    - tyler.cit262.com # this is a dns record that has not been created yet - we need to creat this first
    
